name: Notification cron

on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

jobs:
  trigger-notification-jobs:
    runs-on: ubuntu-latest
    steps:
      - name: Check room capacity
        run: curl --fail --show-error "${{ secrets.NOTIFICATION_URL }}/cron/check-capacity"

      - name: Process reservation notifications
        run: curl --fail --show-error "${{ secrets.NOTIFICATION_URL }}/cron/process-reservations"
